# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('Nid', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=256)),
                ('RealName', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=256)),
            ],
        ),
    ]
