# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_idc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[(b'float', b'Float'), (b'string', b'String'), (b'integer', b'Integer')], max_length=50)),
                ('unit', models.CharField(default=b'%', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
