# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('graph_type', models.CharField(max_length=50)),
                ('datasets', models.ManyToManyField(to='web.Items')),
            ],
        ),
    ]
