# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_formulas_operators'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(default=b'char', max_length=32, verbose_name='\u6570\u636e\u7c7b\u578b')),
                ('threshold', models.CharField(max_length=64, verbose_name='\u9600\u503c')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Formulas', verbose_name='\u8fd0\u7b97\u51fd\u6570')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Items', verbose_name='\u76d1\u63a7\u503c')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Operators', verbose_name='\u8fd0\u7b97\u7b26')),
            ],
        ),
    ]
