# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('check_interval', models.IntegerField(default=300)),
                ('description', models.TextField()),
                ('conditons', models.ManyToManyField(blank=True, null=True, to='web.Conditions', verbose_name='\u9600\u503c\u5217\u8868')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Services')),
            ],
        ),
    ]
