# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_trunkservers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trunkservers',
            name='ip_address',
            field=models.GenericIPAddressField(default=b''),
        ),
    ]
