# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_trunkservers_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('recovery_notice', models.BooleanField(default=True)),
                ('recovery_subject', models.CharField(max_length=100)),
                ('recovery_message', models.CharField(max_length=250)),
                ('enabled', models.BooleanField(default=True)),
                ('condition_list', models.ManyToManyField(to='web.Conditions')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField(default=b'', unique=True)),
                ('port', models.IntegerField(default=b'22')),
                ('os', models.CharField(default=b'linux', max_length=20, verbose_name=b'Operating System')),
                ('status_monitor_on', models.BooleanField(default=True)),
                ('snmp_on', models.BooleanField(default=True)),
                ('snmp_version', models.CharField(default=b'2c', max_length=10)),
                ('snmp_community_name', models.CharField(default=b'public', max_length=50)),
                ('snmp_security_level', models.CharField(default=b'auth', max_length=50)),
                ('snmp_auth_protocol', models.CharField(default=b'MD5', max_length=50)),
                ('snmp_user', models.CharField(default=b'triaquae_snmp', max_length=50)),
                ('snmp_pass', models.CharField(default=b'my_pass', max_length=50)),
                ('custom_services', models.ManyToManyField(blank=True, null=True, to='web.Services')),
                ('group', models.ManyToManyField(blank=True, null=True, to='web.Group')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Idc')),
                ('template_list', models.ManyToManyField(blank=True, null=True, to='web.Templates')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_via', models.CharField(choices=[(b'email', b'Email'), (b'sms', b'SMS')], max_length=30)),
                ('notice_times', models.IntegerField(default=5)),
                ('notice_interval', models.IntegerField(default=300, verbose_name=b'notice_interval(sec)')),
                ('send_to_groups', models.ManyToManyField(to='web.Group')),
                ('send_to_users', models.ManyToManyField(to='web.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='operation_list',
            field=models.ManyToManyField(to='web.Operations'),
        ),
    ]
