# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20160721_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('host_status', models.CharField(default=b'Unkown', max_length=10)),
                ('ping_status', models.CharField(default=b'Unkown', max_length=100)),
                ('last_check', models.CharField(default=b'N/A', max_length=100)),
                ('host_uptime', models.CharField(default=b'Unkown', max_length=50)),
                ('attempt_count', models.IntegerField(default=0)),
                ('breakdown_count', models.IntegerField(default=0)),
                ('up_count', models.IntegerField(default=0)),
                ('snmp_alert_count', models.IntegerField(default=0)),
                ('availability', models.CharField(default=0, max_length=20)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.Host')),
            ],
        ),
    ]
